# 项目名
name: dumi deploy test

# 只有在master分支发生push事件时触发
on:
  push:
    branches:
      - main

# 工作流
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境

    steps:
      # 拉代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 下载node，我这里指定了15.x，这个版本可随意，高于dumi规定的node版本即可
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'pnpm'

      # 打包代码
      - name: Build Project
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      # 部署到github
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: build # 打包的内容放到build分支下
          folder: dist
